# Generated by Django 5.2.16 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_populate_problem_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="slug",
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
