# Generated by Django 5.2.16 on 2026-07-26

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0004_enforce_problem_slug_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=6, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("PLAYING", "Playing"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="WAITING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=900)),
                ("is_draw", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="won_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_host", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="matches.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_players",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField()),
                ("title_snapshot", models.CharField(max_length=200)),
                ("statement_snapshot", models.TextField()),
                ("starter_code_snapshot", models.TextField(blank=True)),
                ("difficulty_snapshot", models.CharField(max_length=20)),
                ("first_solved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "first_solver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_solved_problems",
                        to="matches.matchplayer",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_problems",
                        to="matches.match",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_problems",
                        to="problems.problem",
                    ),
                ),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_seconds__gt", 0)),
                name="match_duration_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=~(
                    models.Q(("winner__isnull", False)) & models.Q(("is_draw", True))
                ),
                name="match_winner_or_draw_not_both",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchplayer",
            constraint=models.UniqueConstraint(
                fields=("match", "user"),
                name="matchplayer_match_user_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchproblem",
            constraint=models.UniqueConstraint(
                fields=("match", "problem"),
                name="matchproblem_match_problem_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchproblem",
            constraint=models.UniqueConstraint(
                fields=("match", "order"),
                name="matchproblem_match_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchproblem",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gte", 1)),
                name="matchproblem_points_gte_1",
            ),
        ),
        migrations.AddIndex(
            model_name="matchproblem",
            index=models.Index(
                fields=["match", "first_solver"], name="matchproblem_solver_idx"
            ),
        ),
    ]
