# Generated by Django 5.2.16 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[("PYTHON", "Python")],
                        default="PYTHON",
                        max_length=20,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("WRONG_ANSWER", "Wrong answer"),
                            ("COMPILATION_ERROR", "Compilation error"),
                            ("RUNTIME_ERROR", "Runtime error"),
                            ("TIME_LIMIT_EXCEEDED", "Time limit exceeded"),
                            ("INTERNAL_ERROR", "Internal error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=25,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("judge_token", models.CharField(blank=True, max_length=100)),
                ("runtime_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("memory_kb", models.PositiveIntegerField(blank=True, null=True)),
                ("judge_message", models.TextField(blank=True)),
                ("is_score_processed", models.BooleanField(db_index=True, default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="matches.match",
                    ),
                ),
                (
                    "match_problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="matches.matchproblem",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="matches.matchplayer",
                    ),
                ),
            ],
            options={"ordering": ["-received_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PlayerProblemProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_solved", models.BooleanField(db_index=True, default=False)),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                ("base_points_awarded", models.PositiveIntegerField(default=0)),
                ("first_solve_bonus_awarded", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_progress",
                        to="matches.submission",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_progress",
                        to="matches.match",
                    ),
                ),
                (
                    "match_problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_progress",
                        to="matches.matchproblem",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_progress",
                        to="matches.matchplayer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playerproblemprogress",
            constraint=models.UniqueConstraint(
                fields=("player", "match_problem"),
                name="progress_player_matchproblem_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerproblemprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("first_solve_bonus_awarded__in", [0, 1])),
                name="progress_first_bonus_0_or_1",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["match", "player"], name="submission_match_player_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["match_problem", "received_at"], name="submission_problem_rcvd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerproblemprogress",
            index=models.Index(
                fields=["match", "player", "is_solved"], name="progress_match_player_sol_idx"
            ),
        ),
    ]
