# Generated by Django 5.2.16 on 2026-07-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0002_submission_playerproblemprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="finish_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TIMEOUT", "Hết giờ"),
                    ("ALL_SOLVED", "Cả hai đã giải hết bài"),
                    ("SURRENDER", "Đầu hàng"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="surrendered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="surrendered_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(("finish_reason", "SURRENDER"))
                    | models.Q(("surrendered_by__isnull", False))
                ),
                name="match_surrender_has_player",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("surrendered_by__isnull", True))
                    | models.Q(("finish_reason", "SURRENDER"))
                ),
                name="match_surrender_player_reason",
            ),
        ),
    ]
