# Generated by Django 5.2.16 on 2026-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_restore_match_capacity_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
