"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, *, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, *, default=""):
    return [
        item.strip()
        for item in os.getenv(name, default).split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG")

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
)
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'problems',
    'accounts',
    'matches',
    'operations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.getenv("DJANGO_DB_PATH", BASE_DIR / "db.sqlite3")),
        'OPTIONS': {
            'timeout': int(os.getenv("DJANGO_SQLITE_TIMEOUT", "20")),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(
    os.getenv("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles")
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT")
SESSION_COOKIE_SECURE = env_bool("DJANGO_SECURE_COOKIES")
CSRF_COOKIE_SECURE = env_bool("DJANGO_SECURE_COOKIES")
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = env_bool("DJANGO_HSTS_PRELOAD")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "lobby"
LOGOUT_REDIRECT_URL = "login"

EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("DJANGO_EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_bool("DJANGO_EMAIL_USE_SSL")
EMAIL_TIMEOUT = int(os.getenv("DJANGO_EMAIL_TIMEOUT_SECONDS", "10"))
DEFAULT_FROM_EMAIL = os.getenv(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "CodeHehe <no-reply@localhost>",
)
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT_SECONDS", "3600"))
EMAIL_VERIFICATION_TIMEOUT_SECONDS = int(
    os.getenv("EMAIL_VERIFICATION_TIMEOUT_SECONDS", "300")
)
PENDING_REGISTRATION_RETENTION_SECONDS = int(
    os.getenv("PENDING_REGISTRATION_RETENTION_SECONDS", "7200")
)
ACCOUNT_EMAIL_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("ACCOUNT_EMAIL_RATE_LIMIT_WINDOW_SECONDS", "3600")
)
ACCOUNT_EMAIL_RATE_LIMIT_PER_IP = int(
    os.getenv("ACCOUNT_EMAIL_RATE_LIMIT_PER_IP", "10")
)
ACCOUNT_EMAIL_RATE_LIMIT_PER_ADDRESS = int(
    os.getenv("ACCOUNT_EMAIL_RATE_LIMIT_PER_ADDRESS", "3")
)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured(
        "DJANGO_EMAIL_USE_TLS and DJANGO_EMAIL_USE_SSL cannot both be enabled."
    )
for setting_name in (
    "EMAIL_PORT",
    "EMAIL_TIMEOUT",
    "PASSWORD_RESET_TIMEOUT",
    "EMAIL_VERIFICATION_TIMEOUT_SECONDS",
    "PENDING_REGISTRATION_RETENTION_SECONDS",
    "ACCOUNT_EMAIL_RATE_LIMIT_WINDOW_SECONDS",
    "ACCOUNT_EMAIL_RATE_LIMIT_PER_IP",
    "ACCOUNT_EMAIL_RATE_LIMIT_PER_ADDRESS",
):
    if globals()[setting_name] <= 0:
        raise ImproperlyConfigured(f"{setting_name} must be greater than zero.")
if PENDING_REGISTRATION_RETENTION_SECONDS < EMAIL_VERIFICATION_TIMEOUT_SECONDS:
    raise ImproperlyConfigured(
        "PENDING_REGISTRATION_RETENTION_SECONDS must be greater than or equal "
        "to EMAIL_VERIFICATION_TIMEOUT_SECONDS."
    )

MATCH_PENDING_SUBMISSION_TIMEOUT_SECONDS = int(
    os.getenv("MATCH_PENDING_SUBMISSION_TIMEOUT_SECONDS", "120")
)
MATCH_DURATION_SECONDS = int(os.getenv("MATCH_DURATION_SECONDS", "300"))
if MATCH_DURATION_SECONDS <= 0:
    raise ImproperlyConfigured(
        "MATCH_DURATION_SECONDS must be greater than zero."
    )
MATCH_SUBMIT_RATE_LIMIT = int(os.getenv("MATCH_SUBMIT_RATE_LIMIT", "30"))
MATCH_RUN_RATE_LIMIT = int(os.getenv("MATCH_RUN_RATE_LIMIT", "60"))
MATCH_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("MATCH_RATE_LIMIT_WINDOW_SECONDS", "60")
)
MATCH_INTEGRITY_ENABLED = env_bool("MATCH_INTEGRITY_ENABLED", default=True)
MATCH_INTEGRITY_HEARTBEAT_SECONDS = int(
    os.getenv("MATCH_INTEGRITY_HEARTBEAT_SECONDS", "10")
)
MATCH_INTEGRITY_IGNORE_BELOW_SECONDS = int(
    os.getenv("MATCH_INTEGRITY_IGNORE_BELOW_SECONDS", "1")
)
MATCH_INTEGRITY_STRIKE_SECONDS = int(
    os.getenv("MATCH_INTEGRITY_STRIKE_SECONDS", "3")
)
MATCH_INTEGRITY_FLAG_STRIKES = int(
    os.getenv("MATCH_INTEGRITY_FLAG_STRIKES", "2")
)
MATCH_INTEGRITY_FLAG_TOTAL_SECONDS = int(
    os.getenv("MATCH_INTEGRITY_FLAG_TOTAL_SECONDS", "10")
)
MATCH_INTEGRITY_CONNECTION_GAP_SECONDS = int(
    os.getenv("MATCH_INTEGRITY_CONNECTION_GAP_SECONDS", "30")
)
MATCH_INTEGRITY_RATE_LIMIT = int(
    os.getenv("MATCH_INTEGRITY_RATE_LIMIT", "30")
)
MATCH_INTEGRITY_MAX_BATCH_SIZE = int(
    os.getenv("MATCH_INTEGRITY_MAX_BATCH_SIZE", "20")
)
for setting_name in (
    "MATCH_INTEGRITY_HEARTBEAT_SECONDS",
    "MATCH_INTEGRITY_STRIKE_SECONDS",
    "MATCH_INTEGRITY_FLAG_STRIKES",
    "MATCH_INTEGRITY_FLAG_TOTAL_SECONDS",
    "MATCH_INTEGRITY_CONNECTION_GAP_SECONDS",
    "MATCH_INTEGRITY_RATE_LIMIT",
    "MATCH_INTEGRITY_MAX_BATCH_SIZE",
):
    if globals()[setting_name] <= 0:
        raise ImproperlyConfigured(f"{setting_name} must be greater than zero.")
if MATCH_INTEGRITY_IGNORE_BELOW_SECONDS < 0:
    raise ImproperlyConfigured(
        "MATCH_INTEGRITY_IGNORE_BELOW_SECONDS must be zero or greater."
    )
if MATCH_INTEGRITY_STRIKE_SECONDS <= MATCH_INTEGRITY_IGNORE_BELOW_SECONDS:
    raise ImproperlyConfigured(
        "MATCH_INTEGRITY_STRIKE_SECONDS must exceed the ignore threshold."
    )
if MATCH_INTEGRITY_CONNECTION_GAP_SECONDS <= MATCH_INTEGRITY_HEARTBEAT_SECONDS:
    raise ImproperlyConfigured(
        "MATCH_INTEGRITY_CONNECTION_GAP_SECONDS must exceed heartbeat seconds."
    )
if MATCH_INTEGRITY_MAX_BATCH_SIZE > 20:
    raise ImproperlyConfigured(
        "MATCH_INTEGRITY_MAX_BATCH_SIZE must not exceed 20."
    )
READINESS_CHECK_JUDGE0 = env_bool("READINESS_CHECK_JUDGE0")

AI_REVIEW_ENABLED = env_bool("AI_REVIEW_ENABLED")
AI_REVIEW_PROVIDER = os.getenv("AI_REVIEW_PROVIDER", "groq").strip().lower()
if AI_REVIEW_PROVIDER not in {"groq", "gemini", "openrouter"}:
    raise ImproperlyConfigured(
        "AI_REVIEW_PROVIDER must be groq, gemini, or openrouter."
    )
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip()
GEMINI_API_KEY = (
    os.getenv("GEMINI_API_KEY", "") or os.getenv("GOOGLE_API_KEY", "")
).strip()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "").strip()
OPENROUTER_HTTP_REFERER = os.getenv(
    "OPENROUTER_HTTP_REFERER",
    "https://codehehe.eastasia.cloudapp.azure.com",
).strip()
OPENROUTER_APP_TITLE = os.getenv("OPENROUTER_APP_TITLE", "CodeHehe").strip()
default_ai_review_model = {
    "groq": "openai/gpt-oss-120b",
    "gemini": "gemini-2.5-flash-lite",
    "openrouter": "openrouter/free",
}[AI_REVIEW_PROVIDER]
AI_REVIEW_MODEL = os.getenv("AI_REVIEW_MODEL", default_ai_review_model).strip()
AI_REVIEW_REASONING_EFFORT = os.getenv(
    "AI_REVIEW_REASONING_EFFORT",
    "none",
).strip()
if AI_REVIEW_REASONING_EFFORT not in {"none", "low", "medium", "high"}:
    raise ImproperlyConfigured(
        "AI_REVIEW_REASONING_EFFORT must be none, low, medium, or high."
    )
AI_REVIEW_PROMPT_VERSION = os.getenv("AI_REVIEW_PROMPT_VERSION", "v2").strip()
AI_REVIEW_MAX_OUTPUT_TOKENS = int(
    os.getenv("AI_REVIEW_MAX_OUTPUT_TOKENS", "2048")
)
AI_REVIEW_MAX_ATTEMPTS = int(os.getenv("AI_REVIEW_MAX_ATTEMPTS", "5"))
AI_REVIEW_MAX_MANUAL_RETRIES = int(
    os.getenv("AI_REVIEW_MAX_MANUAL_RETRIES", "1")
)
AI_REVIEW_REQUESTS_PER_MINUTE = int(
    os.getenv("AI_REVIEW_REQUESTS_PER_MINUTE", "15")
)
AI_REVIEW_STALE_SECONDS = int(os.getenv("AI_REVIEW_STALE_SECONDS", "300"))
AI_REVIEW_MAX_SOURCE_CHARS = int(
    os.getenv("AI_REVIEW_MAX_SOURCE_CHARS", "16000")
)
for setting_name in (
    "AI_REVIEW_MAX_OUTPUT_TOKENS",
    "AI_REVIEW_MAX_ATTEMPTS",
    "AI_REVIEW_REQUESTS_PER_MINUTE",
    "AI_REVIEW_STALE_SECONDS",
    "AI_REVIEW_MAX_SOURCE_CHARS",
):
    if globals()[setting_name] <= 0:
        raise ImproperlyConfigured(f"{setting_name} must be greater than zero.")
if AI_REVIEW_MAX_MANUAL_RETRIES < 0:
    raise ImproperlyConfigured(
        "AI_REVIEW_MAX_MANUAL_RETRIES must be zero or greater."
    )

OPERATIONS_DASHBOARD_REFRESH_SECONDS = int(
    os.getenv("OPERATIONS_DASHBOARD_REFRESH_SECONDS", "15")
)
OPERATIONS_DASHBOARD_HIDDEN_REFRESH_SECONDS = int(
    os.getenv("OPERATIONS_DASHBOARD_HIDDEN_REFRESH_SECONDS", "60")
)
OPERATIONS_DASHBOARD_SNAPSHOT_CACHE_SECONDS = int(
    os.getenv("OPERATIONS_DASHBOARD_SNAPSHOT_CACHE_SECONDS", "10")
)
OPERATIONS_JUDGE_HEALTH_CACHE_SECONDS = int(
    os.getenv("OPERATIONS_JUDGE_HEALTH_CACHE_SECONDS", "30")
)
OPERATIONS_JUDGE_SLOW_MS = int(os.getenv("OPERATIONS_JUDGE_SLOW_MS", "1000"))
OPERATIONS_WAITING_STALE_SECONDS = int(
    os.getenv("OPERATIONS_WAITING_STALE_SECONDS", "1800")
)
OPERATIONS_MATCH_GRACE_SECONDS = int(
    os.getenv("OPERATIONS_MATCH_GRACE_SECONDS", "60")
)
OPERATIONS_AI_QUEUE_WARNING_SECONDS = int(
    os.getenv("OPERATIONS_AI_QUEUE_WARNING_SECONDS", "600")
)
OPERATIONS_AI_WORKER_STALE_SECONDS = int(
    os.getenv("OPERATIONS_AI_WORKER_STALE_SECONDS", "90")
)
OPERATIONS_SWEEPER_STALE_SECONDS = int(
    os.getenv("OPERATIONS_SWEEPER_STALE_SECONDS", "60")
)
OPERATIONS_AI_FAILURE_WINDOW_SECONDS = int(
    os.getenv("OPERATIONS_AI_FAILURE_WINDOW_SECONDS", "900")
)
OPERATIONS_AI_FAILURE_WARNING_COUNT = int(
    os.getenv("OPERATIONS_AI_FAILURE_WARNING_COUNT", "3")
)
OPERATIONS_INTEGRITY_ALERT_WINDOW_SECONDS = int(
    os.getenv("OPERATIONS_INTEGRITY_ALERT_WINDOW_SECONDS", "86400")
)
for setting_name in (
    "OPERATIONS_DASHBOARD_REFRESH_SECONDS",
    "OPERATIONS_DASHBOARD_HIDDEN_REFRESH_SECONDS",
    "OPERATIONS_DASHBOARD_SNAPSHOT_CACHE_SECONDS",
    "OPERATIONS_JUDGE_HEALTH_CACHE_SECONDS",
    "OPERATIONS_JUDGE_SLOW_MS",
    "OPERATIONS_WAITING_STALE_SECONDS",
    "OPERATIONS_MATCH_GRACE_SECONDS",
    "OPERATIONS_AI_QUEUE_WARNING_SECONDS",
    "OPERATIONS_AI_WORKER_STALE_SECONDS",
    "OPERATIONS_SWEEPER_STALE_SECONDS",
    "OPERATIONS_AI_FAILURE_WINDOW_SECONDS",
    "OPERATIONS_AI_FAILURE_WARNING_COUNT",
    "OPERATIONS_INTEGRITY_ALERT_WINDOW_SECONDS",
):
    if globals()[setting_name] <= 0:
        raise ImproperlyConfigured(f"{setting_name} must be greater than zero.")
