"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, *, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, *, default=""):
    return [
        item.strip()
        for item in os.getenv(name, default).split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG")

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
)
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'problems',
    'accounts',
    'matches',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.getenv("DJANGO_DB_PATH", BASE_DIR / "db.sqlite3")),
        'OPTIONS': {
            'timeout': int(os.getenv("DJANGO_SQLITE_TIMEOUT", "20")),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(
    os.getenv("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles")
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT")
SESSION_COOKIE_SECURE = env_bool("DJANGO_SECURE_COOKIES")
CSRF_COOKIE_SECURE = env_bool("DJANGO_SECURE_COOKIES")
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = env_bool("DJANGO_HSTS_PRELOAD")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "lobby"
LOGOUT_REDIRECT_URL = "login"

MATCH_PENDING_SUBMISSION_TIMEOUT_SECONDS = int(
    os.getenv("MATCH_PENDING_SUBMISSION_TIMEOUT_SECONDS", "120")
)
MATCH_DURATION_SECONDS = int(os.getenv("MATCH_DURATION_SECONDS", "300"))
if MATCH_DURATION_SECONDS <= 0:
    raise ImproperlyConfigured(
        "MATCH_DURATION_SECONDS must be greater than zero."
    )
MATCH_SUBMIT_RATE_LIMIT = int(os.getenv("MATCH_SUBMIT_RATE_LIMIT", "30"))
MATCH_RUN_RATE_LIMIT = int(os.getenv("MATCH_RUN_RATE_LIMIT", "60"))
MATCH_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("MATCH_RATE_LIMIT_WINDOW_SECONDS", "60")
)
READINESS_CHECK_JUDGE0 = env_bool("READINESS_CHECK_JUDGE0")

AI_REVIEW_ENABLED = env_bool("AI_REVIEW_ENABLED")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip()
AI_REVIEW_MODEL = os.getenv("AI_REVIEW_MODEL", "openai/gpt-oss-120b").strip()
AI_REVIEW_REASONING_EFFORT = os.getenv(
    "AI_REVIEW_REASONING_EFFORT",
    "low",
).strip()
if AI_REVIEW_REASONING_EFFORT not in {"low", "medium", "high"}:
    raise ImproperlyConfigured(
        "AI_REVIEW_REASONING_EFFORT must be low, medium, or high."
    )
AI_REVIEW_PROMPT_VERSION = os.getenv("AI_REVIEW_PROMPT_VERSION", "v2").strip()
AI_REVIEW_MAX_OUTPUT_TOKENS = int(
    os.getenv("AI_REVIEW_MAX_OUTPUT_TOKENS", "800")
)
AI_REVIEW_MAX_ATTEMPTS = int(os.getenv("AI_REVIEW_MAX_ATTEMPTS", "5"))
AI_REVIEW_STALE_SECONDS = int(os.getenv("AI_REVIEW_STALE_SECONDS", "300"))
AI_REVIEW_MAX_SOURCE_CHARS = int(
    os.getenv("AI_REVIEW_MAX_SOURCE_CHARS", "16000")
)
for setting_name in (
    "AI_REVIEW_MAX_OUTPUT_TOKENS",
    "AI_REVIEW_MAX_ATTEMPTS",
    "AI_REVIEW_STALE_SECONDS",
    "AI_REVIEW_MAX_SOURCE_CHARS",
):
    if globals()[setting_name] <= 0:
        raise ImproperlyConfigured(f"{setting_name} must be greater than zero.")
