# Generated by Django 5.2 on 2026-09-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("PENDING", "Đang chờ"), ("ACCEPTED", "Đã đồng ý"), ("DECLINED", "Đã từ chối"), ("CANCELLED", "Đã hủy")], db_index=True, default="PENDING", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("requester", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friend_requests_sent", to=settings.AUTH_USER_MODEL)),
                ("user_high", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friend_requests_as_high", to=settings.AUTH_USER_MODEL)),
                ("user_low", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friend_requests_as_low", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_high", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friendships_as_high", to=settings.AUTH_USER_MODEL)),
                ("user_low", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friendships_as_low", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("blocked", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_blocks_received", to=settings.AUTH_USER_MODEL)),
                ("blocker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_blocks_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("show_presence_to_friends", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="social_presence", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["user_id"]},
        ),
        migrations.AddConstraint(model_name="friendrequest", constraint=models.CheckConstraint(condition=models.Q(("user_low__lt", models.F("user_high"))), name="friendrequest_canonical_pair")),
        migrations.AddConstraint(model_name="friendrequest", constraint=models.CheckConstraint(condition=models.Q(models.Q(("responded_at__isnull", True), ("status", "PENDING")), models.Q(models.Q(("status", "PENDING"), _negated=True), ("responded_at__isnull", False)), _connector="OR"), name="friendrequest_response_state")),
        migrations.AddConstraint(model_name="friendrequest", constraint=models.UniqueConstraint(condition=models.Q(("status", "PENDING")), fields=("user_low", "user_high"), name="friendrequest_one_pending_pair")),
        migrations.AddIndex(model_name="friendrequest", index=models.Index(fields=["requester", "status", "created_at"], name="friendreq_sender_state_idx")),
        migrations.AddIndex(model_name="friendrequest", index=models.Index(fields=["status", "expires_at"], name="friendreq_state_expiry_idx")),
        migrations.AddConstraint(model_name="friendship", constraint=models.CheckConstraint(condition=models.Q(("user_low__lt", models.F("user_high"))), name="friendship_canonical_pair")),
        migrations.AddConstraint(model_name="friendship", constraint=models.UniqueConstraint(fields=("user_low", "user_high"), name="friendship_unique_pair")),
        migrations.AddConstraint(model_name="userblock", constraint=models.CheckConstraint(condition=models.Q(("blocker", models.F("blocked")), _negated=True), name="userblock_distinct_users")),
        migrations.AddConstraint(model_name="userblock", constraint=models.UniqueConstraint(fields=("blocker", "blocked"), name="userblock_unique_direction")),
    ]
