# Generated by Django 5.2.16 on 2026-09-09 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requester", models.F("user_low")),
                    ("requester", models.F("user_high")),
                    _connector="OR",
                ),
                name="friendrequest_requester_in_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="friendrequest_valid_expiry",
            ),
        ),
    ]
