# Generated by Django 5.2.16 on 2026-09-11 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0026_update_skill_microcopy"),
        ("social", "0002_friendrequest_friendrequest_requester_in_pair_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMatchInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pair_key", models.CharField(editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang chờ"),
                            ("ACCEPTED", "Đã đồng ý"),
                            ("DECLINED", "Đã từ chối"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_match_invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_match_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_invitation_origin",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["invitee", "status", "expires_at"],
                        name="directinvite_recipient_idx",
                    ),
                    models.Index(
                        fields=["inviter", "created_at"], name="directinvite_sender_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("inviter", models.F("invitee")), _negated=True
                        ),
                        name="directinvite_distinct_users",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="directinvite_valid_expiry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("responded_at__isnull", True), ("status", "PENDING")
                            ),
                            models.Q(
                                models.Q(("status", "PENDING"), _negated=True),
                                ("responded_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="directinvite_response_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("new_match__isnull", False), ("status", "ACCEPTED")
                            ),
                            models.Q(
                                models.Q(("status", "ACCEPTED"), _negated=True),
                                ("new_match__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="directinvite_accepted_match",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("pair_key",),
                        name="directinvite_one_pending_pair",
                    ),
                ],
            },
        ),
    ]
